/// <reference types="nativewind/types" />
/// <reference path="./global.d.ts" />

// NOTE: This file should not be edited and should be committed with your source code. It is generated by NativeWind.
